#!/bin/bash -eu

# EWID
LOGLEVEL=${LOGLEVEL=W}

log() {
	ll=$1
	if [ $LOGLEVEL == I ]; then
		if [[ "D" == *$ll* ]]; then
			return
		fi
	elif [ $LOGLEVEL == W ]; then
		if [[ "DI" == *$ll* ]]; then
			return
		fi
	elif [ $LOGLEVEL == E ]; then
		if [[ "DIW" == *$ll* ]]; then
			return
		fi
	fi
	echo $@
}

if [ -e $(dirname "$0")/config.$HOSTNAME ]; then
	log I loading config $(dirname "$0")/config.$HOSTNAME
	source $(dirname "$0")/config.$HOSTNAME
else
	log I loading config $(dirname "$0")/config
	source $(dirname "$0")/config
fi

CP=${CP=cp}
STAT=${STAT=stat}
CHMOD=${CHMOD=chmod}
CHOWN=${CHOWN=chown}
MKTEMP=${MKTEMP=mktemp}

if [ ${1:0:1} == '/' ]; then
	dir=$(dirname "$1")
	file=$(basename "$1")
else
	mf=$PWD/$1
	dir=$(dirname "$mf")
	file=$(basename "$mf")
fi

log D will try to create file $file in directory $dir

if [[ ! ("$(realpath --relative-to $HOME $dir)" =~ "../") ]]; then
	tdir=HOME/$(realpath --relative-to $HOME $dir)
else
	tdir=$dir
fi
log D dir in target is $tdir

export SRC=$DATA/$tdir/$file
# SRC will be changed if a class-file is used
export ORIG_SRC=$SRC
export DEST=$dir/$file
export CLASSES=''

[ -e $DATA/classes.$HOSTNAME ] && export CLASSES=$(cat $DATA/classes.$HOSTNAME)

function find_class_file {
	for i in $HOSTNAME $CLASSES DEFAULT; do
		if [ -e $ORIG_SRC/$i ]; then
		   echo $ORIG_SRC/$i
		   return
	   fi
   done
}

function find_mode_file {
	for i in $HOSTNAME $CLASSES DEFAULT; do
		if [ -e $ORIG_SRC/file-mode.$i ]; then
		   echo $ORIG_SRC/file-mode.$i
		   return
	   fi
	done
	echo $ORIG_SRC/file-mode
}

function find_executable_class_file {
	for i in $HOSTNAME $CLASSES DEFAULT; do
		if [ -x $ORIG_SRC/$1.$i ]; then
		   echo $ORIG_SRC/$1.$i
		   return
	   fi
   done
}

if [ ! -d "$SRC" ]; then
	log E $DEST is not under yacss control
	exit 1
fi

if [ -e $DEST -a ! -f $DEST ]; then
	log E $DEST is a directory!
	exit 1
fi

export SRC=$(find_class_file)
export PRE=$(find_executable_class_file pre)
export INSTEAD=$(find_executable_class_file instead)
export POST=$(find_executable_class_file post)
export MODE=$(sed -e "s/CURRENT_USER/$USER/;s/CURRENT_GROUP/$(id -gn)/" "$(find_mode_file)")

if [ -z "$SRC" -a -z "$INSTEAD" ]; then
	log E $DEST does not exist for these classes
	exit 1
fi

if [ -n "$INSTEAD" ]; then
	export SRC=$($MKTEMP)
	$INSTEAD > $SRC
fi

if [ -e $DEST ] && diff $SRC $DEST > /dev/null; then
	log I $DEST already there and new.
else
	if [ -e $DEST ]; then
		$CP -v $DEST $ORIG_SRC/$HOSTNAME.$(date +%Y%m%d%H%M)
	fi

	[ -n "$PRE" ] && $PRE

	$CP -v $SRC $DEST

	[ -n "$POST" ] && $POST
fi

if [ "$($STAT -c "%U:%G %a" $DEST)" != "$MODE" ]; then
	echo Setting mode to $MODE
	$CHOWN -v ${MODE% *} $DEST
	$CHMOD -v ${MODE#* } $DEST
fi
